### ISSUE TITLE
Cannot track running job's progress

### ISSUE THREAD

**Issue by ghost** [stripe/timberlake#11]
I'm running the teragen with hadoop v2.4.1 and yarn like this: 

```
/usr/bin/yarn jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar \
 teragen \
 -Dmapreduce.job.maps=1024 \
 10995116278 \
 /user/root/benchmark/terasort/teragen1T
```

 timberlake log says

```
2014/12/05 14:25:14.541161 Running jobs: 1
2014/12/05 14:25:14.541187 Jobs in cache: 4
2014/12/05 14:25:14.541197 Goroutines: 32
2014/12/05 14:25:14.541358 Finished jobs: 0
2014/12/05 14:25:14.551641 invalid character 'T' looking for beginning of value
2014/12/05 14:25:16.540800 Running jobs: 1
2014/12/05 14:25:16.540833 Jobs in cache: 4
2014/12/05 14:25:16.540843 Goroutines: 32
2014/12/05 14:25:16.541159 Finished jobs: 0
2014/12/05 14:25:16.551071 invalid character 'T' looking for beginning of value
```

and Web page could not show any progress of the running job. But after job done, the result page shows normally.

**Comment by dug-stripe** [comment]
We improved the error message in https://github.com/stripe/timberlake/pull/74
and hot-swap the RM url as of https://github.com/stripe/timberlake/pull/80 (we have a less-hacky long-term fix in mind involving reading conf files, but this will do the trick for now)
