### ISSUE TITLE
Support for secure hadoop urls

### ISSUE THREAD

**Issue by kunickiaj** [stripe/timberlake#15]
Not sure if you guys have a better place for posting questions like this, or if you've tried this on a hadoop setup using https for the hadoop web uis.

Is there a way to configure the app to use https urls for things like the NameNode, RM, etc?

I'm guessing there's some configuration required for SSL certificates.

**Comment by dug-stripe** [comment]
Timing out here. Please re-open, ideally with a stack trace or such, if you find this doesn't work as expected.
