### ISSUE TITLE
Feature request: a way to discover and view counters

### ISSUE THREAD

**Issue by snoble** [stripe/timberlake#20]
hadoop jobs can have counters that can give insight into the progress of the job. It would be nice to be able to see these in timberlake. But there are a lot of default hadoop and cascading counters that probably could make this an eye sore. So it would be nice to be able to see what counters exist while excluding these (unless specially requested).

**Comment by dug-stripe** [comment]
This has been fixed for a while, currently available via the `/counters` endpoint (see https://github.com/stripe/timberlake/pull/62). Ideally the links would be a bit more discoverable though (i.e. they would look like links).
