### ISSUE TITLE
Ordering by duration doesn't work

### ISSUE THREAD

**Issue by buryat** [stripe/timberlake#9]
See the screenshot:
![screenshot 2014-12-04 19 50 00](https://cloud.githubusercontent.com/assets/721503/5309217/d1f22656-7bee-11e4-9c26-73a968fa0270.png)

**Comment by tglstory** [comment]
this is solved now.

**Comment by jbalogh** [comment]
Fixed in https://github.com/stripe/timberlake/pull/40
